name: Setup Terragrunt

inputs:
  terragrunt-version:
    description: 'The version of Terragrunt to install'
    required: true
    default: '0.67.9'
  opentofu-version:
    description: 'The version of OpenTofu to install'
    required: true
    default: '1.8.3'
  ssh-private-key:
    description: 'The SSH private key to use for fetching Terragrunt modules'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Install Dependencies
      env:
        TERRAGRUNT_VERSION: ${{ inputs.terragrunt-version }}
        OPENTOFU_VERSION: ${{ inputs.opentofu-version }}
      shell: bash
      run: |
        sudo mkdir -p /usr/local/bin
        curl -sSfL -o /tmp/terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v${TERRAGRUNT_VERSION}/terragrunt_linux_amd64
        sudo install -c -m 0755 /tmp/terragrunt /usr/local/bin
        curl -sSfL -o /tmp/opentofu.tar.gz https://github.com/opentofu/opentofu/releases/download/v${OPENTOFU_VERSION}/tofu_${OPENTOFU_VERSION}_linux_amd64.tar.gz
        tar -xzf /tmp/opentofu.tar.gz -C /tmp
        sudo install -c -m 0755 /tmp/tofu /usr/local/bin

    - name: Configure SSH
      if: ${{ inputs.ssh-private-key != '' }}
      shell: bash
      run: |
        # Create a temporary directory for the SSH socket
        mkdir -p $HOME/.tmp/ssh

        # Start the SSH agent and capture its PID
        eval $(ssh-agent -a $HOME/.tmp/ssh/agent.sock)

        # Add the SSH private key to the SSH agent
        echo "${{ inputs.ssh-private-key }}" | tr -d '\r' | ssh-add -

        # Set the SSH_AUTH_SOCK environment variable
        echo "SSH_AUTH_SOCK=$HOME/.tmp/ssh/agent.sock" >> $GITHUB_ENV
