name: Setup Terragrunt

inputs:
  terragrunt-version:
    description: 'The version of Terragrunt to install'
    required: true
    default: '0.67.9'
  opentofu-version:
    description: 'The version of OpenTofu to install'
    required: true
    default: '1.8.2'

runs:
  using: 'composite'
  steps:
    - name: Install Dependencies
      env:
        TERRAGRUNT_VERSION: ${{ inputs.terragrunt-version }}
        OPENTOFU_VERSION: ${{ inputs.opentofu-version }}
      run: |
        sudo mkdir -p /usr/local/bin
        curl -sSfL -o /tmp/terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v${TERRAGRUNT_VERSION}/terragrunt_linux_amd64
        sudo install -c -m 0755 /tmp/terragrunt /usr/local/bin
        curl -sSfL -o /tmp/opentofu.tar.gz https://github.com/opentofu/opentofu/releases/download/v${OPENTOFU_VERSION}/tofu_${OPENTOFU_VERSION}_linux_amd64.tar.gz
        tar -xzf /tmp/opentofu.tar.gz -C /tmp
        sudo install -c -m 0755 /tmp/tofu /usr/local/bin
